# Generated by Django 5.0.3 on 2024-06-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_noteadvertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteadvertisement',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
