# Generated by Django 5.0.3 on 2024-06-21 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_category_sub'),
        ('options', '0003_noteadvertisement_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_view', to='content.advertisement')),
            ],
        ),
    ]
