# Generated by Django 5.0.3 on 2024-09-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_category_sub'),
        ('options', '0004_viewadvertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewadvertisement',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viewadvertisement',
            name='viewed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='viewadvertisement',
            unique_together={('advertisement', 'user_ip')},
        ),
    ]
